[package]
name = "grasp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
rand = { version = "0.8.5" }
rayon = "1.6"
clap = { version = "4.0", features = ["derive"] }
